name: Tacit Knowledge + Reality Pedagogy
description: an annotated bibliography of resources for further research
title: Resource Hub
url: "https.cb451.github.io"
url: "https.cb451.github.io/papers.html"
