name: Tacit Knowledge + Reality Pedagogy Index
description: an annotated bibliography of resources for further research
title: Resource Index
url: "https.cb451.github.io"
title: Resource Index - Papers
url: "https.cb451.github.io/papers.html"
