name: Tacit Knowledge + Reality Pedagogy
description: an annotated bibliography of resources for further research
title: Resource Hub
url: "https.personalknowledge.github.io"
title: Resource Hub - Papers
url: "https.personalknowledge.github.io/papers.html"
